
# HTTP Server
server:
  port: 9301   # HTTP (Tomcat) port

#Spring Boot Configuration
spring:
  application:
    name: autor-microservice

# Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Loggin Mongo Querys
logging:
  level:    org.springframework.data.mongodb.core.MongoTemplate: DEBUG