
# HTTP Server
server:
  port: 9202   # HTTP (Tomcat) port

# Spring Boot Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libreria?useSSL=false&serverTimezone=UTC
    username: root
    password: Greg123$$Mysql
  jpa:
    generate-ddl: true
    show-sql: true

# Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
